/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as TermosdeusoIndexRouteImport } from './pages/termosdeuso/index'
import { Route as SignupIndexRouteImport } from './pages/signup/index'
import { Route as ResetpasswordIndexRouteImport } from './pages/resetpassword/index'
import { Route as ProfileIndexRouteImport } from './pages/profile/index'
import { Route as PoliticadeprivacidadeIndexRouteImport } from './pages/politicadeprivacidade/index'
import { Route as OpportunitiesIndexRouteImport } from './pages/opportunities/index'
import { Route as MyopportunitiesIndexRouteImport } from './pages/myopportunities/index'
import { Route as MydonationsIndexRouteImport } from './pages/mydonations/index'
import { Route as MycampaignsIndexRouteImport } from './pages/mycampaigns/index'
import { Route as LoginIndexRouteImport } from './pages/login/index'
import { Route as FavoritesIndexRouteImport } from './pages/favorites/index'
import { Route as ErrorIndexRouteImport } from './pages/error/index'
import { Route as DonationsIndexRouteImport } from './pages/donations/index'
import { Route as CampaignsIndexRouteImport } from './pages/campaigns/index'
import { Route as AboutusIndexRouteImport } from './pages/aboutus/index'
import { Route as HomeIndexRouteImport } from './pages/_Home/index'
import { Route as OpportunitiesOpportunityIdRouteImport } from './pages/opportunities/_Opportunity/$id'
import { Route as DonationsDonationIdRouteImport } from './pages/donations/_Donation/$id'
import { Route as CampaignsCampaignIdRouteImport } from './pages/campaigns/_Campaign/$id'

const TermosdeusoIndexRoute = TermosdeusoIndexRouteImport.update({
  id: '/termosdeuso/',
  path: '/termosdeuso/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetpasswordIndexRoute = ResetpasswordIndexRouteImport.update({
  id: '/resetpassword/',
  path: '/resetpassword/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticadeprivacidadeIndexRoute =
  PoliticadeprivacidadeIndexRouteImport.update({
    id: '/politicadeprivacidade/',
    path: '/politicadeprivacidade/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyopportunitiesIndexRoute = MyopportunitiesIndexRouteImport.update({
  id: '/myopportunities/',
  path: '/myopportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const MydonationsIndexRoute = MydonationsIndexRouteImport.update({
  id: '/mydonations/',
  path: '/mydonations/',
  getParentRoute: () => rootRouteImport,
} as any)
const MycampaignsIndexRoute = MycampaignsIndexRouteImport.update({
  id: '/mycampaigns/',
  path: '/mycampaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesIndexRoute = FavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorIndexRoute = ErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsIndexRoute = DonationsIndexRouteImport.update({
  id: '/donations/',
  path: '/donations/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutusIndexRoute = AboutusIndexRouteImport.update({
  id: '/aboutus/',
  path: '/aboutus/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/_Home/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesOpportunityIdRoute =
  OpportunitiesOpportunityIdRouteImport.update({
    id: '/opportunities/_Opportunity/$id',
    path: '/opportunities/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const DonationsDonationIdRoute = DonationsDonationIdRouteImport.update({
  id: '/donations/_Donation/$id',
  path: '/donations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/_Campaign/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/aboutus': typeof AboutusIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/donations': typeof DonationsIndexRoute
  '/error': typeof ErrorIndexRoute
  '/favorites': typeof FavoritesIndexRoute
  '/login': typeof LoginIndexRoute
  '/mycampaigns': typeof MycampaignsIndexRoute
  '/mydonations': typeof MydonationsIndexRoute
  '/myopportunities': typeof MyopportunitiesIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/politicadeprivacidade': typeof PoliticadeprivacidadeIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/resetpassword': typeof ResetpasswordIndexRoute
  '/signup': typeof SignupIndexRoute
  '/termosdeuso': typeof TermosdeusoIndexRoute
  '/campaigns/$id': typeof CampaignsCampaignIdRoute
  '/donations/$id': typeof DonationsDonationIdRoute
  '/opportunities/$id': typeof OpportunitiesOpportunityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof HomeIndexRoute
  '/aboutus': typeof AboutusIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/donations': typeof DonationsIndexRoute
  '/error': typeof ErrorIndexRoute
  '/favorites': typeof FavoritesIndexRoute
  '/login': typeof LoginIndexRoute
  '/mycampaigns': typeof MycampaignsIndexRoute
  '/mydonations': typeof MydonationsIndexRoute
  '/myopportunities': typeof MyopportunitiesIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/politicadeprivacidade': typeof PoliticadeprivacidadeIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/resetpassword': typeof ResetpasswordIndexRoute
  '/signup': typeof SignupIndexRoute
  '/termosdeuso': typeof TermosdeusoIndexRoute
  '/campaigns/$id': typeof CampaignsCampaignIdRoute
  '/donations/$id': typeof DonationsDonationIdRoute
  '/opportunities/$id': typeof OpportunitiesOpportunityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_Home/': typeof HomeIndexRoute
  '/aboutus/': typeof AboutusIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/donations/': typeof DonationsIndexRoute
  '/error/': typeof ErrorIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/mycampaigns/': typeof MycampaignsIndexRoute
  '/mydonations/': typeof MydonationsIndexRoute
  '/myopportunities/': typeof MyopportunitiesIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/politicadeprivacidade/': typeof PoliticadeprivacidadeIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/resetpassword/': typeof ResetpasswordIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/termosdeuso/': typeof TermosdeusoIndexRoute
  '/campaigns/_Campaign/$id': typeof CampaignsCampaignIdRoute
  '/donations/_Donation/$id': typeof DonationsDonationIdRoute
  '/opportunities/_Opportunity/$id': typeof OpportunitiesOpportunityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aboutus'
    | '/campaigns'
    | '/donations'
    | '/error'
    | '/favorites'
    | '/login'
    | '/mycampaigns'
    | '/mydonations'
    | '/myopportunities'
    | '/opportunities'
    | '/politicadeprivacidade'
    | '/profile'
    | '/resetpassword'
    | '/signup'
    | '/termosdeuso'
    | '/campaigns/$id'
    | '/donations/$id'
    | '/opportunities/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aboutus'
    | '/campaigns'
    | '/donations'
    | '/error'
    | '/favorites'
    | '/login'
    | '/mycampaigns'
    | '/mydonations'
    | '/myopportunities'
    | '/opportunities'
    | '/politicadeprivacidade'
    | '/profile'
    | '/resetpassword'
    | '/signup'
    | '/termosdeuso'
    | '/campaigns/$id'
    | '/donations/$id'
    | '/opportunities/$id'
  id:
    | '__root__'
    | '/_Home/'
    | '/aboutus/'
    | '/campaigns/'
    | '/donations/'
    | '/error/'
    | '/favorites/'
    | '/login/'
    | '/mycampaigns/'
    | '/mydonations/'
    | '/myopportunities/'
    | '/opportunities/'
    | '/politicadeprivacidade/'
    | '/profile/'
    | '/resetpassword/'
    | '/signup/'
    | '/termosdeuso/'
    | '/campaigns/_Campaign/$id'
    | '/donations/_Donation/$id'
    | '/opportunities/_Opportunity/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  AboutusIndexRoute: typeof AboutusIndexRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  DonationsIndexRoute: typeof DonationsIndexRoute
  ErrorIndexRoute: typeof ErrorIndexRoute
  FavoritesIndexRoute: typeof FavoritesIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MycampaignsIndexRoute: typeof MycampaignsIndexRoute
  MydonationsIndexRoute: typeof MydonationsIndexRoute
  MyopportunitiesIndexRoute: typeof MyopportunitiesIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  PoliticadeprivacidadeIndexRoute: typeof PoliticadeprivacidadeIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ResetpasswordIndexRoute: typeof ResetpasswordIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  TermosdeusoIndexRoute: typeof TermosdeusoIndexRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
  DonationsDonationIdRoute: typeof DonationsDonationIdRoute
  OpportunitiesOpportunityIdRoute: typeof OpportunitiesOpportunityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termosdeuso/': {
      id: '/termosdeuso/'
      path: '/termosdeuso'
      fullPath: '/termosdeuso'
      preLoaderRoute: typeof TermosdeusoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resetpassword/': {
      id: '/resetpassword/'
      path: '/resetpassword'
      fullPath: '/resetpassword'
      preLoaderRoute: typeof ResetpasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politicadeprivacidade/': {
      id: '/politicadeprivacidade/'
      path: '/politicadeprivacidade'
      fullPath: '/politicadeprivacidade'
      preLoaderRoute: typeof PoliticadeprivacidadeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myopportunities/': {
      id: '/myopportunities/'
      path: '/myopportunities'
      fullPath: '/myopportunities'
      preLoaderRoute: typeof MyopportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mydonations/': {
      id: '/mydonations/'
      path: '/mydonations'
      fullPath: '/mydonations'
      preLoaderRoute: typeof MydonationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mycampaigns/': {
      id: '/mycampaigns/'
      path: '/mycampaigns'
      fullPath: '/mycampaigns'
      preLoaderRoute: typeof MycampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/': {
      id: '/favorites/'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/': {
      id: '/error/'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations/': {
      id: '/donations/'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof DonationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aboutus/': {
      id: '/aboutus/'
      path: '/aboutus'
      fullPath: '/aboutus'
      preLoaderRoute: typeof AboutusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_Home/': {
      id: '/_Home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/_Opportunity/$id': {
      id: '/opportunities/_Opportunity/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations/_Donation/$id': {
      id: '/donations/_Donation/$id'
      path: '/donations/$id'
      fullPath: '/donations/$id'
      preLoaderRoute: typeof DonationsDonationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/_Campaign/$id': {
      id: '/campaigns/_Campaign/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  AboutusIndexRoute: AboutusIndexRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  DonationsIndexRoute: DonationsIndexRoute,
  ErrorIndexRoute: ErrorIndexRoute,
  FavoritesIndexRoute: FavoritesIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MycampaignsIndexRoute: MycampaignsIndexRoute,
  MydonationsIndexRoute: MydonationsIndexRoute,
  MyopportunitiesIndexRoute: MyopportunitiesIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  PoliticadeprivacidadeIndexRoute: PoliticadeprivacidadeIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ResetpasswordIndexRoute: ResetpasswordIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  TermosdeusoIndexRoute: TermosdeusoIndexRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
  DonationsDonationIdRoute: DonationsDonationIdRoute,
  OpportunitiesOpportunityIdRoute: OpportunitiesOpportunityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
